name: lando-mysql-80
services:
  defaults:
    type: mysql-v4-8.0

# This is important because it lets lando know to test against the plugin in this repo
# DO NOT REMOVE THIS!
plugins:
  "@lando/mysql": ./../../
